### ISSUE TITLE
Feature request: Hur mycket salt ska man ha?

### ISSUE THREAD

**Issue by johan-bjareholt** [Lilja/IcaRis#1]
Ibland glömmer jag salta och ibland saltar jag för mycket, vad är det perfekta mängden salt?

**Comment by Lilja** [comment]
Skalan: `För 2dl ris skall det saltas 3krm`
5 krm = 1 tsk
3 krm = 1/3 tsk
3/2 = salt per deciliter ris
` (Mängd ris i dl * salt-scala) / 5 ) `

Test case:
Vatten: 3 dl 
Ris: 5dl

5 * (3/2) / 5 = 0.6 tsk

Stämmer detta?
